Update sspm

diff --git a/sspm b/sspm
--- a/sspm
+++ b/sspm
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 ###################################################################################################
 #  this script is part of Epsilon(sspm) - https://jpsspm.github.io/sspm                           #
-#  Copyright (C) 2021-2025 Joe Packar    (joepackar@gmail.com)                                    #
+#  Copyright (C) 2021-2026 Joe Packar    (joepackar@gmail.com)                                    #
 #                                                                                                 #
 #      **** a package manager for linux-based Operating Systems built from scratch ****           #
 #                                                                                                 #
@@ -111,12 +111,12 @@ if [[ "$LINE" == 'PKGDTB_DIGIT0=("")' || "$LINE" == 'PKGDTB_DIGIT0=()' \
 if [[ -z "$SOURCES" || -z "$DESTDIR" ]]; then
 case "$lang" in
 fr_*)
-printf "Vous devez installer manuellement ces paquets:\n\e[4mwhich\e[0m, \e[4mzstd\e[0m, \e[4mlibarchive\e[0m, \e[4mpkg-config\e[0m, \e[4mprocps\e[0m \
+printf "Vous devez installer manuellement ces paquets:\n\e[4mwhich\e[0m, \e[4mzstd\e[0m, \e[4mlibarchive\e[0m, \e[4mpkgconf\e[0m, \e[4mprocps\e[0m \
 et \e[4me2fsprogs\e[0m\ndans un r"$e_acute"pertoire temporaire pour faire fonctionner sspm\n\n\e[2m%1ssi vous voulez que cela se fasse automatiquement\n\
 %1sexportez ces deux variables dans votre shell:\n ex: export \e[0m\e[1mSOURCES\e[0m\e[2m='/dir/containing/sources'\n\
 %1sex: export \e[0m\e[1mDESTDIR\e[0m\e[2m='/dir/to_install/temp_packages'\n%1spuis r"$e_acute"ex"$e_acute"cutez votre commande\n\n\
 %1sveuillez vous assurer que vous disposez de ces fichiers sources\n%1savec les versions suivantes ou ult"$e_acute"rieures: \
-libarchive v3.6.2, zstd v1.5.2\n%1spkg-config v0.29.2, which v2.21, procps-ng v4.0.2 et e2fsprogs v1.46.5\n\n\
+libarchive v3.8.6, zstd v1.5.7\n%1spkgconf v2.5.1, which v2.23, procps-ng v4.0.6 et e2fsprogs v1.47.4\n\n\
 %1ssi vous avez d"$e_acute"j"$a_grave" install"$e_acute" tous ces paquets, mettez "$a_grave" jour et exportez\n\
 %1sla variable 'PATH' dans le shell ou sourcez le fichier .bashrc\n%1spour que ces paquets soient visibles dans l'environnement\e[0m\n\n"
 [[ ! -v "SOURCES" && -v "DESTDIR" ]] && printf "%1sveuillez initialiser la variable '\e[91mSOURCES\e[0m'\n\n" && exit 1
@@ -124,12 +124,12 @@ libarchive v3.6.2, zstd v1.5.2\n%1spkg-config v0.29.2, which v2.21, procps-ng v4
 ;;
 tr_TR) ;;
 en_*|*)
-printf "You have to manually install these packages:\n\e[4mwhich\e[0m, \e[4mzstd\e[0m, \e[4mlibarchive\e[0m, \e[4mpkg-config\e[0m, \e[4mprocps\e[0m \
+printf "You have to manually install these packages:\n\e[4mwhich\e[0m, \e[4mzstd\e[0m, \e[4mlibarchive\e[0m, \e[4mpkgconf\e[0m, \e[4mprocps\e[0m \
 and \e[4me2fsprogs\e[0m\nin a temporary directory to make sspm work\n\n\e[2m%1sthis can be done automatically by simply setting\n\
 %1sthese two variables in your shell:\n ex: export \e[0m\e[1mSOURCES\e[0m\e[2m='/dir/containing/sources'\n\
 %1sex: export \e[0m\e[1mDESTDIR\e[0m\e[2m='/dir/to_install/temp_packages'\n%1sthen rerun your command\n\n\
 %1smake sure that you have these source files\n%1swith the following versions or later: \
-libarchive v3.6.2, zstd v1.5.2\n%1spkg-config v0.29.2, which v2.21, procps-ng v4.0.2 and e2fsprogs v1.46.5\n\n\
+libarchive v3.8.6, zstd v1.5.7\n%1spkgconf v2.5.1, which v2.23, procps-ng v4.0.6 and e2fsprogs v1.47.4\n\n\
 %1sif you have already installed these packages, update and re-export\n\
 %1sthe 'PATH' variable in your shell or simply source the .bashrc file\n%1sfor these packages to be visible in the environment\e[0m\n\n"
 [[ ! -v "SOURCES" && -v "DESTDIR" ]] && printf "%1splease initialize the '\e[91mSOURCES\e[0m' variable\n\n" && exit 1
@@ -212,8 +212,8 @@ TEMP='/tmp'; BASHRC='.bashrc'
                *) ./configure --prefix=/usr --with-internal-glib --disable-host-tool;; esac && \
                make && make install; [[ $? != 0 ]] && BUILD_STATUS=1; cd $TEMP && rm -r $CD_DIR;
                fi; [[ $BUILD_STATUS && $BUILD_STATUS = 1 ]] && case "$lang" in
-               fr_*) printf '\n\n\e[91merreur\e[0m:  « pkg-config »  compilation '$e_acute'chou'$e_acute'e\n\n'; exit 1;;
-               en_*|*) printf '\n\n\e[91merror\e[0m:  « pkg-config »  build failed\n\n'; exit 1;;
+               fr_*) printf '\n\n\e[91merreur\e[0m:  « pkgconf »  compilation '$e_acute'chou'$e_acute'e\n\n'; exit 1;;
+               en_*|*) printf '\n\n\e[91merror\e[0m:  « pkgconf »  build failed\n\n'; exit 1;;
                esac; if [[ $REL_TYPE ]]; then ln -sfv pkgconf   "$DESTDIR/usr/bin/pkg-config"; \
                SLINK0="$(find $DESTDIR -name libpkgconf.so.* -type l -print | head -1)"
                ln -sfv $DESTDIR/usr/lib/$(readlink $SLINK0) /usr/lib/$(basename $SLINK0); fi
@@ -438,7 +438,7 @@ STRIPPKG="${STRIPPKG:-$STRIP_PKG}"
 
 sspm_version() {
 if [[ "$RANDOM" =~ $"6" ]]; then
-printf "%csspm $SSPM_VER%2sCopyright (C) 2021-2025. Joe Packar\n"
+printf "%csspm $SSPM_VER%2sCopyright (C) 2021-2026. Joe Packar\n"
 elif [[ "$RANDOM" =~ ^"5" || "$RANDOM" =~ ^[1_1_]+$ ]]; then
 case "$lang" in
 fr_*)
@@ -459,7 +459,7 @@ elif [[ "$RANDOM" =~ $"7" || "$RANDOM" =~ ^[6_2_]+$ ]]; then
 case "$lang" in
 fr_*)
 printf "%13ssspm  v$SSPM_VER\n\
-%6s\e[1mS\e[0m%6sCopyright (C) 2021-2025 Free Software Foundation, Inc.\n\
+%6s\e[1mS\e[0m%6sCopyright (C) 2021-2026 Free Software Foundation, Inc.\n\
 %6s\e[1mS\e[0m%6sLicense GPLv3+: GNU GPL version 3 ou ult"$e_acute"rieure\n\
 %6s\e[1mP\e[0m\n\
 %6s\e[1mM\e[0m%6sCe programme est un logiciel libre: libre a modifier ou a redistribuer\n\
@@ -468,7 +468,7 @@ printf "%13ssspm  v$SSPM_VER\n\
 tr_TR) ;;
 en_*|*)
 printf "%13ssspm  v$SSPM_VER\n\
-%6s\e[1mS\e[0m%6sCopyright (C) 2021-2025 Free Software Foundation, Inc.\n\
+%6s\e[1mS\e[0m%6sCopyright (C) 2021-2026 Free Software Foundation, Inc.\n\
 %6s\e[1mS\e[0m%6sLicense GPLv3+: GNU GPL version 3 or later\n\
 %6s\e[1mP\e[0m\n\
 %6s\e[1mM\e[0m%6sThis is free software: free to change and to redistribute\n\
@@ -481,14 +481,14 @@ case "$lang" in fr_*) printf "sspm v$SSPM_VER\n" ;; tr_TR) ;; en_*|*) printf "ss
 elif [[ "$RANDOM" =~ ^"3" ]]; then
 case "$lang" in
 fr_*)
-printf "%c\t\t\t\tsspm  v$SSPM_VER\n%3s\e[90m-------------------\e[0m\t\tCopyright (C) 2021-2025 Joe Packar\n\
+printf "%c\t\t\t\tsspm  v$SSPM_VER\n%3s\e[90m-------------------\e[0m\t\tCopyright (C) 2021-2026 Joe Packar\n\
 %2s\e[90m|\e[0m%19s\e[90m|\e[0m\n\
 %2s\e[90m|\e[0m%6s\e[1m\e[90mS%1sS\e[0m%1s\e[1mP%1sM\e[0m%6s\e[90m|\e[0m\t\tCe programme est un logiciel libre;\n\
 %2s\e[90m|%19s|\e[0m\t\tvous pouvez le redistribuer ou le modifier\e[90m\n%3s-------------------\e[0m\
 \t\tvoir les sources pour les conditions de copie.\v\n" ;;
 tr_TR) ;;
 en_*|*)
-printf "%c\t\t\t\tsspm  v$SSPM_VER\n%3s\e[90m-------------------\e[0m\t\tCopyright (C) 2021-2025 Joe Packar\n\
+printf "%c\t\t\t\tsspm  v$SSPM_VER\n%3s\e[90m-------------------\e[0m\t\tCopyright (C) 2021-2026 Joe Packar\n\
 %2s\e[90m|\e[0m%19s\e[90m|\e[0m\n\
 %2s\e[90m|\e[0m%6s\e[1m\e[90mS%1sS\e[0m%1s\e[1mP%1sM\e[0m%6s\e[90m|\e[0m\t\tYes you right, sspm is free.\n\
 %2s\e[90m|%19s|\e[0m\t\tyou can redistribute or change it\e[90m\n%3s-------------------\e[0m\
@@ -497,12 +497,12 @@ esac
 elif [[ "$RANDOM" == *0*0* ]]; then
 case "$lang" in
 fr_*)
-printf "%csspm  v$SSPM_VER\nCopyright \xc2\xa9 2021-2025 Free Software Foundation, Inc.\n\
+printf "%csspm  v$SSPM_VER\nCopyright \xc2\xa9 2021-2026 Free Software Foundation, Inc.\n\
 Licence GPLv3+: GNU GPL version 3 ou ult"$e_acute"rieure <https://gnu.org/licenses/gpl.html>.\n\
 Logiciel libre : vous "$e_circumflex"tes libre de le modifier ou de le redistribuer.\n\
 Il n'y a AUCUNE GARANTIE, dans les limites permises par la loi.\v\n"$E_acute"crit par Joe Packar.\n" ;;
 en_*|*)
-printf "%csspm  v$SSPM_VER\nCopyright (C) 2021-2025 Free Software Foundation, Inc.\n\
+printf "%csspm  v$SSPM_VER\nCopyright (C) 2021-2026 Free Software Foundation, Inc.\n\
 License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n\
 This is free software: you are free to change and redistribute it.\n\
 There is NO WARRANTY, to the extent permitted by law.\v\nWritten by Joe Packar.\n" ;;
@@ -529,7 +529,7 @@ case "$lang" in fr_*) printf "sspm v$SSPM_VER\n" ;; tr_TR) ;; en_*|*) printf "ss
 elif [[ "$RANDOM" == 1*9 ]]; then
 case "$lang" in
 fr_*)
-printf "%c\t\t\t\tsspm  v$SSPM_VER\n\t\t\t\tCopyright (C) 2021-2025 Joe Packar\n\
+printf "%c\t\t\t\tsspm  v$SSPM_VER\n\t\t\t\tCopyright (C) 2021-2026 Joe Packar\n\
 %3s-------------------\n%2s|%19s|\t\tCe programme est un logiciel libre;\n\
 %2s|%6s\e[94mS%1sS%1sP%1sM\e[0m%6s|\t\tvous pouvez le redistribuer ou le modifier\n\
 %2s|%19s|\t\tsous les termes de la GNU General Public License\n%3s-------------------\
@@ -537,7 +537,7 @@ printf "%c\t\t\t\tsspm  v$SSPM_VER\n\t\t\t\tCopyright (C) 2021-2025 Joe Packar\n
 %1sversion 3 de la licence, soit\n%32s($a_grave votre choix) toute version ult"$e_acute"rieure.\n" ;;
 tr_TR) ;;
 en_*|*)
-printf "%c\t\t\t\tsspm  v$SSPM_VER\n\t\t\t\tCopyright (C) 2021-2025 Joe Packar\n\
+printf "%c\t\t\t\tsspm  v$SSPM_VER\n\t\t\t\tCopyright (C) 2021-2026 Joe Packar\n\
 %3s-------------------\n%2s|%19s|\t\tthis is free software.\n\
 %2s|%6s\e[94mS%1sS%1sP%1sM\e[0m%6s|\t\tyou are free to change or to redistribute it\n\
 %2s|%19s|\t\tunder the terms of the GNU General Public License\n%3s-------------------\
@@ -565,12 +565,12 @@ esac
 elif [[ -z "$RANDOM" || ! -e "$RANDOM" ]]; then
 case "$lang" in
 fr_*)
-printf "%csspm  v$SSPM_VER\nCopyright \xc2\xa9 2021-2025 Free Software Foundation, Inc.\n\
+printf "%csspm  v$SSPM_VER\nCopyright \xc2\xa9 2021-2026 Free Software Foundation, Inc.\n\
 Licence GPLv3+: GNU GPL version 3 ou ult"$e_acute"rieure <https://gnu.org/licenses/gpl.html>.\n\
 Logiciel libre : vous "$e_circumflex"tes libre de le modifier ou de le redistribuer.\n\
 Il n'y a AUCUNE GARANTIE, dans les limites permises par la loi.\v\n"$E_acute"crit par Joe Packar.\n" ;;
 en_*|*)
-printf "%csspm  v$SSPM_VER\nCopyright (C) 2021-2025 Free Software Foundation, Inc.\n\
+printf "%csspm  v$SSPM_VER\nCopyright (C) 2021-2026 Free Software Foundation, Inc.\n\
 License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n\
 This is free software: you are free to change and redistribute it.\n\
 There is NO WARRANTY, to the extent permitted by law.\v\nWritten by Joe Packar.\n" ;;
@@ -578,14 +578,14 @@ esac
 else
 case "$lang" in
 fr_*)
-printf "%c\t\t\t\tsspm  v$SSPM_VER\n%3s\e[90m-------------------\e[0m\t\tCopyright (C) 2021-2025 Joe Packar\n\
+printf "%c\t\t\t\tsspm  v$SSPM_VER\n%3s\e[90m-------------------\e[0m\t\tCopyright (C) 2021-2026 Joe Packar\n\
 %2s\e[90m|\e[0m%19s\e[90m|\e[0m\n\
 %2s\e[90m|\e[0m%6s\e[1m\e[1mS%1sS\e[0m%1s\e[90mP%1sM\e[0m%6s\e[90m|\e[0m\t\tCe programme est un logiciel libre;\n\
 %2s\e[90m|%19s|\e[0m\t\tvous pouvez le redistribuer ou le modifier\e[90m\n%3s-------------------\e[0m\
 \t\tvoir les sources pour les conditions de copie.\v\n" ;;
 tr_TR) ;;
 en_*|*)
-printf "%c\t\t\t\tsspm  v$SSPM_VER\n%3s\e[90m-------------------\e[0m\t\tCopyright (C) 2021-2025 Joe Packar\n\
+printf "%c\t\t\t\tsspm  v$SSPM_VER\n%3s\e[90m-------------------\e[0m\t\tCopyright (C) 2021-2026 Joe Packar\n\
 %2s\e[90m|\e[0m%19s\e[90m|\e[0m\n\
 %2s\e[90m|\e[0m%6s\e[1m\e[1mS%1sS\e[0m%1s\e[90mP%1sM\e[0m%6s\e[90m|\e[0m\t\tYes you right, sspm is free.\n\
 %2s\e[90m|%19s|\e[0m\t\tyou can redistribute or change it\e[90m\n%3s-------------------\e[0m\
@@ -770,7 +770,7 @@ DESCRIPTION\n\
 %11spar d"$e_acute"faut le r"$e_acute"pertoire de configuration est '~/.config/sspm'\n%11svous avez pas besoin de red"$e_acute"finir cette variable "$a_grave" la prochaine session.\n\n\
 %7s*%1sPATH\n%11svous "$e_circumflex"tes au stade du chroot (c'est-"$a_grave"-dire vous venez de chrooter dans vos outils temporaires).\n\
 %11s'sspm' a besoin de ces paquets: 'bsdtar (libarchive), zstd, coreutils, e2fsprogs, which, tar\n\
-%11spkg-config, grep, sed, xz, gawk, Procps' dans ce environnement pour fonctionner.\n\
+%11spkgconf, grep, sed, xz, gawk, Procps' dans ce environnement pour fonctionner.\n\
 %11squi eux m"$e_circumflex"me doivent "$e_circumflex"tre install"$e_acute"s par 'sspm' dans un ordre d"$e_acute"fini par vous ou votre livre linux.\n\
 %11spour ne pas d"$e_acute"stabiliser vous outils ou corrompre certaines biblioth"$e_grave"ques\n\n\
 %11scr"$e_acute"ez un r"$e_acute"pertoire temporaire puis installez manuellement les paquets list"$e_acute"s ci-dessus\n\
@@ -839,11 +839,11 @@ remarque: si la variable 'tfext' dans le fichier (pkgbuild) est vide,\n\
       Pour plus d'informations, consultez la page d'accueil de sspm\n\
       "$a_grave" l'adresse suivante: https://jpsspm.github.io/sspm/.\n\n\
 \e[1mDROITS D'AUTEUR\e[0m\n\
-            Copyright \xc2\xa9 2021-2025 Free Software Foundation, Inc.\n\
+            Copyright \xc2\xa9 2021-2026 Free Software Foundation, Inc.\n\
             License GPLv3+: GNU GPL version 3 ou ult"$e_acute"rieure <https://gnu.org/licenses/gpl.html>.\n\
             Ce programme est un logiciel libre: vous pouvez le redistribuer ou le modifier.\n\
             Il n'y a AUCUNE GARANTIE, dans la mesure permise par la loi.\v\v\n
-sspm $SSPM_VER%68sJuin 2025%68sSSPM(1)   \n" ;;
+sspm $SSPM_VER%68sMars 2026%68sSSPM(1)   \n" ;;
 tr_TR) ;;
 en_*|*)
 printf "SSPM(1)\n\n\
@@ -920,7 +920,7 @@ DESCRIPTION\n\
 %11sby default its '~/.config/sspm' you don't need to set this variable again at next session\n\n\
 %7s*%1sPATH\n%11syou are at chroot stage (you've just chrooted in your temp environment).\n\
 %11s'sspm' need these packages: 'bsdtar (libarchive), zstd, coreutils, e2fsprogs, which, tar\n\
-%11spkg-config, grep, sed, xz, gawk, procps' in that environment to work.\n\
+%11spkgconf, grep, sed, xz, gawk, procps' in that environment to work.\n\
 %11swhere the same packages must be build with sspm in a specific order. for not breaking libraries\n\n\
 %11screate a temporary directory and install manually the packages listed above\n\
 %11s(only not available packages) in that directory with maximum disabled features.\n\
@@ -981,11 +981,11 @@ note:%5swhatever build function name build_foo() { commands }, foo_build() { com
       repport bugs at https://github.com/jpsspm/sspm/issues/\n\
       home page: https://jpsspm.github.io/sspm/\n\n\
 \e[1mCOPYRIGHT\e[0m\n\
-         Copyright \xc2\xa9 2021-2025 Free Software Foundation, Inc.\n\
+         Copyright \xc2\xa9 2021-2026 Free Software Foundation, Inc.\n\
          License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.\n\
          This is free software: you can change and redistribute it.\n\
          There is NO WARRANTY, to the extent permitted by law.\v\v\n
-sspm $SSPM_VER%68sJune 2025%68sSSPM(1)   \n" ;;
+sspm $SSPM_VER%68sMarch 2026%68sSSPM(1)   \n" ;;
 esac
 }
 
@@ -1000,7 +1000,7 @@ printf "\e[93mNB:\e[0m il ya (3) variables tr"$e_grave"s importantes\v\n\
 %7s*%1sSRC\n%10sr"$e_acute"pertoire contenant le ou les fichiers sources (ex: export SRC=~/tout_les_fichiers_sources) \n\n\
 %7s*%1sPATH\n%11svous "$e_circumflex"tes au stade du chroot (c'est-"$a_grave"-dire vous venez de chrooter dans vos outils temporaires).\n\
 %11s'sspm' a besoin de ces paquets: 'bsdtar (libarchive), zstd, coreutils, e2fsprogs, which, tar\n\
-%11spkg-config, grep, sed, xz, gawk, Procps' dans ce environnement pour fonctionner.\n\
+%11spkgconf, grep, sed, xz, gawk, Procps' dans ce environnement pour fonctionner.\n\
 %11squi eux m"$e_circumflex"me doivent "$e_circumflex"tre install"$e_acute"s par 'sspm' dans un ordre d"$e_acute"fini par vous ou votre livre linux.\n\
 %11spour ne pas d"$e_acute"stabiliser vous outils ou corrompre certaines biblioth"$e_grave"ques;\n\n\
 %11scr"$e_acute"ez un r"$e_acute"pertoire temporaire puis installez manuellement les paquets list"$e_acute"s ci-dessus\n\
@@ -1027,7 +1027,7 @@ printf "\e[93mNOTE:\e[0m there are (3) important variables\v\n\
 %7s*%1sSRC\n%10sfetch sources from (ex: export SRC=~/all_sources_files) \n\n\
 %7s*%1sPATH\n%11syou are at chroot stage (you've just chrooted in your temp environment).\n\
 %11s'sspm' need these packages: 'bsdtar (libarchive), zstd, coreutils, e2fsprogs, which, tar\n\
-%11spkg-config, grep, sed, xz, gawk, procps' in that environment to work.\n\
+%11spkgconf, grep, sed, xz, gawk, procps' in that environment to work.\n\
 %11swhere the same packages must be build with sspm in a specific order. for not breaking libraries\n\n\
 %11screate a temporary directory and install manually the packages listed above\n\
 %11s(only not available packages) in that directory with maximum disabled features.\n\
@@ -1066,12 +1066,12 @@ esac
                                  case "$lang" in fr_*)
                                 printf "\e[91m==> ERREUR: \e[0mCertaines d"$e_acute"pendances manquent\n"
                                printf "\e[90massurez vous qu'au minimum ces paquets sont install"$e_acute"s:\e[0m\n"
-                               printf "\e[90mwhich, tar, gawk, grep, pkg-config, find, sed, xz, zstd, libarchive, coreutils, Procps, e2fsprogs\e[0m\n" ;;
+                               printf "\e[90mwhich, tar, gawk, grep, pkgconf, find, sed, xz, zstd, libarchive, coreutils, Procps, e2fsprogs\e[0m\n" ;;
                                tr_TR) ;;
                                en_*|*)
                                printf "\e[91m==> ERROR: \e[0mmissing dependencies\n"
                                printf "\e[2mmake sure to have at leaste these packages installed:\e[0m\n"
-                               printf "\e[2mwhich, tar, gawk, grep, pkg-config, find, sed, xz, zstd, libarchive, coreutils, Procps, e2fsprogs\e[0m\n" ;;
+                               printf "\e[2mwhich, tar, gawk, grep, pkgconf, find, sed, xz, zstd, libarchive, coreutils, Procps, e2fsprogs\e[0m\n" ;;
                                esac
                                printf '\n'
                                printf '\n'
@@ -2934,7 +2934,7 @@ case "$lang" in fr_*) printf '*** lol ***\n' ;; tr_TR) ;; en_*|*) printf '*** so
   else case "$lang" in fr_*) printf "\e[91merreur:\e[0m indiquer un paquet "$a_grave" installer\n" ;;
   tr_TR) ;; en_*|*) printf "\e[91merror:\e[0m  no package specified\n" ;; esac; exit $ERCODE; fi
 ipc_tool -L
-local EMULATED_TERM="$([[ "$(tty)" = '/dev/pts/'* ]] && printf '1')"
+local EMULATED_TERM="$([[ "$(tty 2>/dev/null)" = '/dev/pts/'* ]] && printf '1')"
 ### the default behavior if you install a package with single process '--install' is to scrollback console buffer
 ### [on non-login shell]. remove the command below if you do not want this behavior
 if ! [[ $INT_MODE || $BIMODE || $NOEXIT || ! $FIRST_INIT ]]; then [[ $EMULATED_TERM ]] && printf '\e[2J\e[H'; fi
